const KANJI_DATA = [
  {
    "char": "炎",
    "element": "fire",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 3,
    "def": 2,
    "spd": 2
  },
  {
    "char": "火",
    "element": "fire",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 3,
    "def": 2,
    "spd": 2
  },
  {
    "char": "灼",
    "element": "fire",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 3,
    "def": 2,
    "spd": 2
  },
  {
    "char": "焔",
    "element": "fire",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 3,
    "def": 2,
    "spd": 2
  },
  {
    "char": "爆",
    "element": "fire",
    "role": "attack",
    "rarity": "N",
    "hp": 1,
    "atk": 6,
    "def": 1,
    "spd": 1
  },
  {
    "char": "溶",
    "element": "fire",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 3,
    "def": 2,
    "spd": 2
  },
  {
    "char": "水",
    "element": "water",
    "role": "utility",
    "rarity": "N",
    "hp": 2,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "海",
    "element": "water",
    "role": "utility",
    "rarity": "N",
    "hp": 2,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "波",
    "element": "water",
    "role": "utility",
    "rarity": "N",
    "hp": 2,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "湖",
    "element": "water",
    "role": "utility",
    "rarity": "N",
    "hp": 2,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "泉",
    "element": "water",
    "role": "utility",
    "rarity": "N",
    "hp": 2,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "潮",
    "element": "water",
    "role": "utility",
    "rarity": "N",
    "hp": 2,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "雷",
    "element": "thunder",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 2,
    "spd": 3
  },
  {
    "char": "電",
    "element": "thunder",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 2,
    "spd": 3
  },
  {
    "char": "轟",
    "element": "thunder",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 2,
    "spd": 3
  },
  {
    "char": "稲",
    "element": "thunder",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 2,
    "spd": 3
  },
  {
    "char": "霆",
    "element": "thunder",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 2,
    "spd": 3
  },
  {
    "char": "霹",
    "element": "thunder",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 2,
    "spd": 3
  },
  {
    "char": "風",
    "element": "wind",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "翼",
    "element": "wind",
    "role": "speed",
    "rarity": "N",
    "hp": 0,
    "atk": 3,
    "def": 1,
    "spd": 5
  },
  {
    "char": "羽",
    "element": "wind",
    "role": "speed",
    "rarity": "N",
    "hp": 0,
    "atk": 3,
    "def": 1,
    "spd": 5
  },
  {
    "char": "空",
    "element": "wind",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "嵐",
    "element": "wind",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "旋",
    "element": "wind",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "土",
    "element": "earth",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 3,
    "spd": 2
  },
  {
    "char": "岩",
    "element": "earth",
    "role": "defense",
    "rarity": "N",
    "hp": 3,
    "atk": 2,
    "def": 6,
    "spd": 0
  },
  {
    "char": "地",
    "element": "earth",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 3,
    "spd": 2
  },
  {
    "char": "山",
    "element": "earth",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 3,
    "spd": 2
  },
  {
    "char": "砂",
    "element": "earth",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 3,
    "spd": 2
  },
  {
    "char": "塔",
    "element": "earth",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 3,
    "spd": 2
  },
  {
    "char": "光",
    "element": "light",
    "role": "utility",
    "rarity": "N",
    "hp": 2,
    "atk": 2,
    "def": 3,
    "spd": 2
  },
  {
    "char": "聖",
    "element": "light",
    "role": "heal",
    "rarity": "SR",
    "hp": 4,
    "atk": 1,
    "def": 4,
    "spd": 1
  },
  {
    "char": "輝",
    "element": "light",
    "role": "utility",
    "rarity": "N",
    "hp": 2,
    "atk": 2,
    "def": 3,
    "spd": 2
  },
  {
    "char": "白",
    "element": "light",
    "role": "utility",
    "rarity": "N",
    "hp": 2,
    "atk": 2,
    "def": 3,
    "spd": 2
  },
  {
    "char": "星",
    "element": "light",
    "role": "utility",
    "rarity": "N",
    "hp": 2,
    "atk": 2,
    "def": 3,
    "spd": 2
  },
  {
    "char": "日",
    "element": "light",
    "role": "utility",
    "rarity": "N",
    "hp": 2,
    "atk": 2,
    "def": 3,
    "spd": 2
  },
  {
    "char": "闇",
    "element": "dark",
    "role": "utility",
    "rarity": "N",
    "hp": 0,
    "atk": 3,
    "def": 2,
    "spd": 3
  },
  {
    "char": "影",
    "element": "dark",
    "role": "utility",
    "rarity": "N",
    "hp": 0,
    "atk": 3,
    "def": 2,
    "spd": 3
  },
  {
    "char": "魔",
    "element": "dark",
    "role": "utility",
    "rarity": "SSR",
    "hp": 0,
    "atk": 5,
    "def": 3,
    "spd": 5
  },
  {
    "char": "黒",
    "element": "dark",
    "role": "utility",
    "rarity": "N",
    "hp": 0,
    "atk": 3,
    "def": 2,
    "spd": 3
  },
  {
    "char": "邪",
    "element": "dark",
    "role": "debuff",
    "rarity": "N",
    "hp": 0,
    "atk": 3,
    "def": 1,
    "spd": 3
  },
  {
    "char": "亡",
    "element": "dark",
    "role": "utility",
    "rarity": "N",
    "hp": 0,
    "atk": 3,
    "def": 2,
    "spd": 3
  },
  {
    "char": "鳥",
    "element": "neutral",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "鷹",
    "element": "neutral",
    "role": "utility",
    "rarity": "R",
    "hp": 1,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "鷲",
    "element": "neutral",
    "role": "utility",
    "rarity": "R",
    "hp": 1,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "鳳",
    "element": "fire",
    "role": "utility",
    "rarity": "SSR",
    "hp": 2,
    "atk": 5,
    "def": 3,
    "spd": 3
  },
  {
    "char": "鴉",
    "element": "neutral",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "狼",
    "element": "neutral",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "虎",
    "element": "neutral",
    "role": "utility",
    "rarity": "R",
    "hp": 1,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "犬",
    "element": "neutral",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "猫",
    "element": "neutral",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "熊",
    "element": "neutral",
    "role": "utility",
    "rarity": "R",
    "hp": 1,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "蛇",
    "element": "neutral",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "竜",
    "element": "thunder",
    "role": "utility",
    "rarity": "SR",
    "hp": 1,
    "atk": 3,
    "def": 3,
    "spd": 4
  },
  {
    "char": "龍",
    "element": "thunder",
    "role": "utility",
    "rarity": "SR",
    "hp": 1,
    "atk": 3,
    "def": 3,
    "spd": 4
  },
  {
    "char": "蜥",
    "element": "neutral",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "鰐",
    "element": "neutral",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "蟲",
    "element": "neutral",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "蝶",
    "element": "neutral",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "蜂",
    "element": "neutral",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "蟻",
    "element": "neutral",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "蛾",
    "element": "neutral",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "魚",
    "element": "neutral",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "鯨",
    "element": "neutral",
    "role": "utility",
    "rarity": "R",
    "hp": 1,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "鯱",
    "element": "neutral",
    "role": "utility",
    "rarity": "R",
    "hp": 1,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "鯉",
    "element": "neutral",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "鰻",
    "element": "neutral",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "麒麟",
    "element": "neutral",
    "role": "utility",
    "rarity": "SR",
    "hp": 1,
    "atk": 3,
    "def": 3,
    "spd": 3
  },
  {
    "char": "獅",
    "element": "neutral",
    "role": "utility",
    "rarity": "SR",
    "hp": 1,
    "atk": 3,
    "def": 3,
    "spd": 3
  },
  {
    "char": "狛",
    "element": "neutral",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "牛",
    "element": "neutral",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "羊",
    "element": "neutral",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "猪",
    "element": "neutral",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "馬",
    "element": "neutral",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "鹿",
    "element": "neutral",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "木",
    "element": "earth",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 3,
    "spd": 2
  },
  {
    "char": "森",
    "element": "earth",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 3,
    "spd": 2
  },
  {
    "char": "林",
    "element": "earth",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 3,
    "spd": 2
  },
  {
    "char": "花",
    "element": "neutral",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "草",
    "element": "neutral",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "石",
    "element": "earth",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 3,
    "spd": 2
  },
  {
    "char": "鉄",
    "element": "neutral",
    "role": "defense",
    "rarity": "N",
    "hp": 3,
    "atk": 2,
    "def": 5,
    "spd": 0
  },
  {
    "char": "銀",
    "element": "neutral",
    "role": "utility",
    "rarity": "R",
    "hp": 1,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "金",
    "element": "neutral",
    "role": "utility",
    "rarity": "R",
    "hp": 1,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "銅",
    "element": "neutral",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "峰",
    "element": "earth",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 3,
    "spd": 2
  },
  {
    "char": "谷",
    "element": "earth",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 3,
    "spd": 2
  },
  {
    "char": "崖",
    "element": "earth",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 3,
    "spd": 2
  },
  {
    "char": "島",
    "element": "earth",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 3,
    "spd": 2
  },
  {
    "char": "洞",
    "element": "earth",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 3,
    "spd": 2
  },
  {
    "char": "雲",
    "element": "wind",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "雪",
    "element": "ice",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "霜",
    "element": "ice",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "雨",
    "element": "water",
    "role": "utility",
    "rarity": "N",
    "hp": 2,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "霞",
    "element": "wind",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "月",
    "element": "light",
    "role": "utility",
    "rarity": "N",
    "hp": 2,
    "atk": 2,
    "def": 3,
    "spd": 2
  },
  {
    "char": "天",
    "element": "light",
    "role": "utility",
    "rarity": "N",
    "hp": 2,
    "atk": 2,
    "def": 3,
    "spd": 2
  },
  {
    "char": "剣",
    "element": "neutral",
    "role": "attack",
    "rarity": "N",
    "hp": 1,
    "atk": 5,
    "def": 1,
    "spd": 1
  },
  {
    "char": "刀",
    "element": "neutral",
    "role": "attack",
    "rarity": "N",
    "hp": 1,
    "atk": 5,
    "def": 1,
    "spd": 1
  },
  {
    "char": "槌",
    "element": "neutral",
    "role": "utility",
    "rarity": "R",
    "hp": 1,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "棍",
    "element": "neutral",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "弓",
    "element": "neutral",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "矢",
    "element": "neutral",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "杖",
    "element": "neutral",
    "role": "utility",
    "rarity": "R",
    "hp": 1,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "盾",
    "element": "neutral",
    "role": "defense",
    "rarity": "N",
    "hp": 3,
    "atk": 2,
    "def": 5,
    "spd": 0
  },
  {
    "char": "鎧",
    "element": "neutral",
    "role": "defense",
    "rarity": "R",
    "hp": 3,
    "atk": 2,
    "def": 6,
    "spd": 0
  },
  {
    "char": "爪",
    "element": "neutral",
    "role": "attack",
    "rarity": "N",
    "hp": 1,
    "atk": 5,
    "def": 1,
    "spd": 1
  },
  {
    "char": "牙",
    "element": "neutral",
    "role": "attack",
    "rarity": "N",
    "hp": 1,
    "atk": 5,
    "def": 1,
    "spd": 1
  },
  {
    "char": "槍",
    "element": "neutral",
    "role": "attack",
    "rarity": "N",
    "hp": 1,
    "atk": 5,
    "def": 1,
    "spd": 1
  },
  {
    "char": "鎌",
    "element": "neutral",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "鎖",
    "element": "neutral",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "力",
    "element": "neutral",
    "role": "attack",
    "rarity": "N",
    "hp": 1,
    "atk": 5,
    "def": 1,
    "spd": 1
  },
  {
    "char": "剛",
    "element": "neutral",
    "role": "attack",
    "rarity": "N",
    "hp": 1,
    "atk": 5,
    "def": 1,
    "spd": 1
  },
  {
    "char": "強",
    "element": "neutral",
    "role": "attack",
    "rarity": "N",
    "hp": 1,
    "atk": 5,
    "def": 1,
    "spd": 1
  },
  {
    "char": "速",
    "element": "neutral",
    "role": "speed",
    "rarity": "N",
    "hp": 0,
    "atk": 3,
    "def": 1,
    "spd": 5
  },
  {
    "char": "疾",
    "element": "neutral",
    "role": "speed",
    "rarity": "N",
    "hp": 0,
    "atk": 3,
    "def": 1,
    "spd": 5
  },
  {
    "char": "瞬",
    "element": "neutral",
    "role": "speed",
    "rarity": "N",
    "hp": 0,
    "atk": 3,
    "def": 1,
    "spd": 5
  },
  {
    "char": "知",
    "element": "neutral",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "智",
    "element": "neutral",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "守",
    "element": "neutral",
    "role": "defense",
    "rarity": "N",
    "hp": 3,
    "atk": 2,
    "def": 5,
    "spd": 0
  },
  {
    "char": "堅",
    "element": "neutral",
    "role": "defense",
    "rarity": "N",
    "hp": 3,
    "atk": 2,
    "def": 5,
    "spd": 0
  },
  {
    "char": "癒",
    "element": "neutral",
    "role": "heal",
    "rarity": "N",
    "hp": 2,
    "atk": 1,
    "def": 2,
    "spd": 1
  },
  {
    "char": "命",
    "element": "neutral",
    "role": "heal",
    "rarity": "N",
    "hp": 2,
    "atk": 1,
    "def": 2,
    "spd": 1
  },
  {
    "char": "念",
    "element": "neutral",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "気",
    "element": "neutral",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "心",
    "element": "neutral",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "魂",
    "element": "neutral",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "毒",
    "element": "neutral",
    "role": "debuff",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 1,
    "spd": 2
  },
  {
    "char": "眠",
    "element": "neutral",
    "role": "debuff",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 1,
    "spd": 2
  },
  {
    "char": "乱",
    "element": "neutral",
    "role": "debuff",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 1,
    "spd": 2
  },
  {
    "char": "痺",
    "element": "neutral",
    "role": "debuff",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 1,
    "spd": 2
  },
  {
    "char": "衰",
    "element": "neutral",
    "role": "debuff",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 1,
    "spd": 2
  },
  {
    "char": "呪",
    "element": "neutral",
    "role": "debuff",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 1,
    "spd": 2
  },
  {
    "char": "封",
    "element": "neutral",
    "role": "debuff",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 1,
    "spd": 2
  },
  {
    "char": "破",
    "element": "neutral",
    "role": "attack",
    "rarity": "N",
    "hp": 1,
    "atk": 5,
    "def": 1,
    "spd": 1
  },
  {
    "char": "神",
    "element": "neutral",
    "role": "utility",
    "rarity": "SSR",
    "hp": 2,
    "atk": 3,
    "def": 3,
    "spd": 3
  },
  {
    "char": "王",
    "element": "neutral",
    "role": "utility",
    "rarity": "SR",
    "hp": 1,
    "atk": 3,
    "def": 3,
    "spd": 3
  },
  {
    "char": "帝",
    "element": "neutral",
    "role": "attack",
    "rarity": "SSR",
    "hp": 2,
    "atk": 8,
    "def": 2,
    "spd": 2
  },
  {
    "char": "皇",
    "element": "neutral",
    "role": "utility",
    "rarity": "SSR",
    "hp": 2,
    "atk": 3,
    "def": 3,
    "spd": 3
  },
  {
    "char": "鬼",
    "element": "dark",
    "role": "utility",
    "rarity": "SR",
    "hp": 0,
    "atk": 4,
    "def": 3,
    "spd": 4
  },
  {
    "char": "妖",
    "element": "dark",
    "role": "utility",
    "rarity": "SR",
    "hp": 0,
    "atk": 4,
    "def": 3,
    "spd": 4
  },
  {
    "char": "精",
    "element": "neutral",
    "role": "utility",
    "rarity": "SR",
    "hp": 1,
    "atk": 3,
    "def": 3,
    "spd": 3
  },
  {
    "char": "霊",
    "element": "neutral",
    "role": "heal",
    "rarity": "SR",
    "hp": 3,
    "atk": 1,
    "def": 3,
    "spd": 1
  },
  {
    "char": "創",
    "element": "neutral",
    "role": "utility",
    "rarity": "SSR",
    "hp": 2,
    "atk": 3,
    "def": 3,
    "spd": 3
  },
  {
    "char": "終",
    "element": "neutral",
    "role": "utility",
    "rarity": "SSR",
    "hp": 2,
    "atk": 3,
    "def": 3,
    "spd": 3
  },
  {
    "char": "界",
    "element": "neutral",
    "role": "utility",
    "rarity": "SSR",
    "hp": 2,
    "atk": 3,
    "def": 3,
    "spd": 3
  },
  {
    "char": "虚",
    "element": "neutral",
    "role": "utility",
    "rarity": "SSR",
    "hp": 2,
    "atk": 3,
    "def": 3,
    "spd": 3
  },
  {
    "char": "極",
    "element": "neutral",
    "role": "utility",
    "rarity": "SSR",
    "hp": 2,
    "atk": 3,
    "def": 3,
    "spd": 3
  },
  {
    "char": "零",
    "element": "neutral",
    "role": "utility",
    "rarity": "SSR",
    "hp": 2,
    "atk": 3,
    "def": 3,
    "spd": 3
  },
  {
    "char": "覇",
    "element": "neutral",
    "role": "attack",
    "rarity": "SSR",
    "hp": 2,
    "atk": 8,
    "def": 2,
    "spd": 2
  },
  {
    "char": "冥",
    "element": "dark",
    "role": "utility",
    "rarity": "SSR",
    "hp": 0,
    "atk": 5,
    "def": 3,
    "spd": 5
  },
  {
    "char": "滅",
    "element": "dark",
    "role": "attack",
    "rarity": "SSR",
    "hp": 0,
    "atk": 10,
    "def": 2,
    "spd": 3
  },
  {
    "char": "凰",
    "element": "fire",
    "role": "utility",
    "rarity": "SSR",
    "hp": 2,
    "atk": 5,
    "def": 3,
    "spd": 3
  },
  {
    "char": "将",
    "element": "neutral",
    "role": "attack",
    "rarity": "N",
    "hp": 1,
    "atk": 5,
    "def": 1,
    "spd": 1
  },
  {
    "char": "氷",
    "element": "ice",
    "role": "utility",
    "rarity": "N",
    "hp": 1,
    "atk": 2,
    "def": 2,
    "spd": 2
  },
  {
    "char": "猛",
    "element": "neutral",
    "role": "attack",
    "rarity": "N",
    "hp": 1,
    "atk": 5,
    "def": 1,
    "spd": 1
  },
  {
    "char": "迅",
    "element": "neutral",
    "role": "speed",
    "rarity": "N",
    "hp": 0,
    "atk": 3,
    "def": 1,
    "spd": 5
  }
];

const INSP_MAP = {
  "炎|鳥": "鳳",
  "狼|雷": "神",
  "氷|竜": "魔",
  "炎|龍": "凰",
  "闇|龍": "冥",
  "光|龍": "聖",
  "神|鳳": "覇",
  "凰|覇": "極",
  "極|神": "零",
  "魔|龍": "滅",
  "炎|狼": "猛",
  "雷|鷹": "迅",
  "影|闇": "冥",
  "光|星": "聖",
  "毒|蛇": "邪",
  "剣|龍": "帝",
  "槍|狼": "将",
  "山|火": "爆",
  "水|海": "潮",
  "翼|風": "嵐",
  "闇|魔": "冥",
  "光|聖": "神",
  "神|雷": "覇",
  "炎|神": "凰",
  "水|龍": "海",
  "風|龍": "天",
  "土|龍": "地",
  "光|鳳": "皇",
  "闇|鳳": "冥",
  "剣|炎": "焔",
  "剣|雷": "迅",
  "剣|氷": "霜",
  "炎|虎": "猛",
  "虎|雷": "轟",
  "虎|風": "疾",
  "虎|闇": "邪",
  "光|虎": "聖",
  "神|龍": "帝",
  "神|魔": "覇",
  "皇|龍": "界",
  "界|神": "創",
  "創|界": "終",
  "界|終": "虚",
  "界|虚": "零",
  "神|零": "極",
  "極|魔": "滅",
  "滅|神": "冥",
  "冥|凰": "覇",
  "極|覇": "零"
};
